ALTER TABLE "Reviews" ADD COLUMN "Sweetness" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "Sourness" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "Freshness" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "FlavorBrightness" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "Strength" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "HeatResistance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Reviews" ADD COLUMN "Smokiness" DOUBLE PRECISION NOT NULL DEFAULT 0;
